In [38]:
#find price of a home that has,
#3000 sqr ft area, 3 bedrooms, 40 year old
#2500 sqr ft area, 4 bedrooms, 5 year old

In [39]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [40]:
df =pd.read_csv('homeprices1.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  505000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [41]:
import math
df.bedrooms.median()

4.0

In [42]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())

In [43]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  505000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [44]:
model = linear_model.LinearRegression()
model.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

In [45]:
model.predict([[3000,3,40]])

A:\software\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([399326.07562816])

In [51]:
model.coef_

array([   65.08145094, 31624.82724245, -7233.8023276 ])

In [52]:
model.intercept_

398559.3341942895

In [53]:
65.08145094*3000+31624.82724245*3+-7233.8023276 *40+398559.3341942895

399326.0756376395

In [54]:
model.predict([[2500,4,5]])

A:\software\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([651593.25886822])

In [60]:
#exercise
# 2 yr experience,9 test score, 6 interview score
# 12 yr experience, 10 test score, 10 interview score
# ans 53713.86 and 93747.79

In [103]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


In [105]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [63]:
df = pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [78]:
import pandas as pd

# Assuming you have a DataFrame called 'df' with a column named 'test_score'
median_score = df['test_score(out of 10)'].median()
print(median_score)


8.0


In [79]:
df.describe()

test_score(out of 10)  interview_score(out of 10)    salary($)
count               7.000000                    8.000000      8.00000
mean                7.857143                    7.875000  63000.00000
std                 1.345185                    1.642081  11501.55269
min                 6.000000                    6.000000  45000.00000
25%                 7.000000                    6.750000  57500.00000
50%                 8.000000                    7.500000  63500.00000
75%                 8.500000                    9.250000  70500.00000
max                10.000000                   10.000000  80000.00000

In [125]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(df['test_score(out of 10)'].median())
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [126]:
df.experience = df.experience.fillna('zero')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [127]:
from word2number import w2n

df['experience'] = df['experience'].astype(str)
df['experience'] = df['experience'].apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [128]:
model = linear_model.LinearRegression()
model.fit(df.drop('salary($)',axis='columns'),df['salary($)'])

LinearRegression()

In [129]:
model.predict([[2,9,6]])

A:\software\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [130]:
model.predict([[12,10,10]])

A:\software\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])